[package]
edition = "2021"
name = "quix"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.8" # CLI Parser
home = "0.5.3" # Home path lib
minifier = "0.2.1" # Minifier for HTML, JS, CSS
notify = "4.0.17" # Notify path + file changes
reqwest = {version = "0.11.11", features = ["blocking"]}# HTTP Clientd
serde = {version = "1.0.139", features = ["derive"]}# General Parser
serde_json = "1.0.82" # JSON Parser
walkdir = "2.3.2" # Lib to deep scan dirs 
zip = "0.6.2" # I think its auto explanatory
