[package]
edition = "2021"
name = "quix"
version = "0.1.0"

[dependencies]
clap = "3.2.8"
exitcode = "1.1.2"
home = "0.5.3"
human-panic = "1.0.3"
minifier = "0.2.1"
notify = "4.0.17"
reqwest = {version = "0.11.11", features = ["blocking", "json"]}
serde = {version = "1.0.139", features = ["derive"]}
serde_json = "1.0.82"
walkdir = "2.3.2"
zip = "0.6.2"
